title: OneKash Labs | Open Source Tools & Apps
description: A collection of open source tools and apps
url: "https://openkash.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
